Pelagicore/vagrant-cookbook

deps/debugging-tools.sh
Install valgrind, gdb and strace.
Making it possible to run valgrind when running tests.
=> Install code analysis and debugging tools

system-config/apt-cacher.sh, system-config/select-apt-mirror.sh
select-apt-mirror: only do rm if file exists.
apt-cacher: run apt-get update no matter what
=> Some fixes in system-config scripts

deps/common-build-dependencies.sh, deps/pulseaudio-dependencies.sh, deps/softwarecontainer-dependencies.sh, system-config/select-apt-mirror.sh
Also, builds LXC from source instead of from apt (in case of debian stable),
so easier to build from git.
Also puts the pulse deps from SC in pulse deps (not a hard dep for
softwarecontainer anymore) and adds automake to common deps.
=> Breaks out softwarecontainer deps from common

system-config/select-apt-mirror.sh
If the box is out of date, we can get 404 from apt since the
apt cache will be too old.
=> Do apt-get update before installing netselect-apt

deps/softwarecontainer-dependencies.sh
LXC will no longer build without this
Signed-off-by: Jonatan Pålsson <jonatan.palsson@pelagicore.com>
=> softwarecontainer-dependencies: Add libtool

build/qmake-git-builder.sh, build/qt5-git-builder.sh
This is useful as it allows the developer to change the build flags
or commands. E.g. instead of just installing, the developer could also
execute the check target afterwards for running autotests.
=> Added an optional makecommand argument to the qmake and qt5-git-builder

deps/softwarecontainer-dependencies.sh
LXC introduced a possible bug which causes build problems
for softwarecontainer. This checks out the last known working
commit.
=> SC-deps: Checks out specific lxc commit.

deps/softwarecontainer-dependencies.sh
=> LXC bug fixed upstream, can track stable-2.0 again

deps/sphinx-dependencies.sh
The requests module must be updated for Sphinx 1.5, if not, the
following error is seen:
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.5
making output directory...
Extension error:
Could not import extension sphinx.builders.linkcheck (exception:
cannot import name SSLError)
Signed-off-by: Jonatan Pålsson <jonatan.palsson@pelagicore.com>
=> sphinx-deps: Upgrade requests module

LICENSE.txt, README.md, build/build-documentation.sh, build/clang-code-analysis.sh, build/cmake-builder.sh, build/cmake-git-builder.sh, build/qmake-git-builder.sh, build/qt5-git-builder.sh, deps/softwarecontainer-dependencies.sh
nproc is part of coreutils and will hence always be available, and it is
a bit wasteful not to use parallelism where we can.
Also removed trailing whitespace in some files.
=> Use -j$(nproc) whenever invoking make

system-config/grub-enable-cgroup-memory.sh
This is necessary for using swap extension of cgroup (). 
I.e. to be able to use following :
- memory.memsw.failcnt
- memory.memsw.limit_in_bytes
- memory.memsw.max_usage_in_bytes
- memory.memsw.usage_in_bytes
=> Enable swapaccount option to use cgroup swap extension

deps/developer-tools.sh
Add Clang to be installed when installing developer convenience.
Signed-off-by: Viktor Sjölind <viktor.sjolind@pelagicore.com>
=> Add Clang as developer convenience

build/clang-code-analysis.sh
This helps it being used in for example a Jenkinsfile.
Also the NewDeleteLeaks has no associated checker, so if we remove it we don't have to look at the warnings about that all the time.
=> Renames the report name from clang to a fixed name

deps/yocto.sh
If this is not installed, you may see errors like the following:
(/home/vagrant/drivecx_yocto/sources/poky/meta/recipes-gnome/gobject-introspection/gobject-introspection_1.46.0.bb,
do_compile) failed with exit code '1'==> default: | /home/vagrant/drivecx_yocto/build/tmp/work/aarch64-gnu-linux/gobject-introspection/1.46.0-r0/build/g-ir-scanner-qemuwrapper: 6: /home/vagrant/drivecx_yocto/build/tmp/work/aarch64-gnu-linux/gobject-introspection/1.46.0-r0/build/g-ir-scanner-qemuwrapper: /home/vagrant/drivecx_yocto/build/tmp/work/aarch64-gnu-linux/gobject-introspection/1.46.0-r0/build/g-ir-scanner-qemuwrapper: 6: /home/vagrant/drivecx_yocto/build/tmp/work/aarch64-gnu-linux/gobject-introspection/1.46.0-r0/build/g-ir-scanner-qemuwrapper: /home/vagrant/drivecx_yocto/build/tmp/work/aarch64-gnu-linux/ …
=> deps/yocto.sh: Add qemu-user

build/clang-code-analysis.sh
=> Remove alpha.unix.MallocWithAnnotations as it's not available

system-config/select-apt-mirror.sh
If we try to download old packages that don't exist we will wind up with a broken Vagrantfile
=> Update so we don't download old binaries

deps/softwarecontainer-dependencies.sh
=> sc-deps: remove dbus-c++ (no longer used)

deps/sphinx-dependencies.sh
Without this we can't generate PDFs.
=> sphinx-dependencies.sh: add latexmk

deps/pytest-and-dbus-testing-dependencies.sh
With this change we prefer python3 over python2
=> pytest deps: order of pip/pip3 install matters.

yocto/runquemu-smoke-test.sh
Since we need to have tunctl in our sysroot before running runqemu-gen-tapdevs,
bitbake qemu-helper-native should be executed first.
=> Fix procedures execution order in runquemu-smoke-tests.sh

yocto/shortlog.sh
Still keep -e since it will exit as soon as any line in the script fails
Signed-off-by: Chuan Jin <cjin@luxoft.com>
=> Use set -ex to have verbose print

yocto/build-esdk.sh
The extensible sdk is being pushed from yocto and Intel to make developing in yocto more accessible.
=> Add support to building the extensible sdk

yocto/fetch-sources-for-recipes.sh
fetchall target is obsolete: https://wiki.yoctoproject.org/wiki/FutureMigrationGuide#Bitbake_changes
Signed-off-by: Oleksandr Kravchuk <oleksandr.kravchuk@pelagicore.com>
=> fetch-sources-for-recipes: adapt to Yocto 2.5

yocto/shortlog.sh
This line was probably there for debugging reasons: any difference
between the manifests is anyway going to be printed in greater detail in
the get_changes() function.
=> shortlog.sh: do not print the manifest diff

muxpi/rpi/dut.sh, muxpi/rpi/set-up-image.sh
set-up-image: This is the main script which downloads the image, makes
it ready for fota, and flashes it via fota. Once its flashed, it calls
dut.sh.
dut.sh: Send the commands to DUT and save the log.
=> muxpi: add scripts for flashing and testing RPI

deps/pytest-and-dbus-testing-dependencies.sh
python3-lxc binding is required to run softwarecontainer service tests.
This binding is required after softwarecontainer is updated to use lxc3
version.
Signed-off-by: Tariq Ansari <tansari@luxoft.com>
=> pytest-and-dbus-testing-dependencies: install python3-lxc binding

yocto/json2junit.py
Tests marked as errors were being reported as passing, because the
`ERROR` status was not handled.
Signed-off-by: Alberto Mardegan <amardegan@luxoft.com>
=> json2junit: Handle `ERROR` result status

muxpi/parse_image.sh
After expanding list of files in archive Mux jobs dont work
To add only image file to archive extention should be added
Signed-off-by: Dmytro Iurchuk <DIurchuk@luxoft.com>
=> muxpi/parse_image.sh: Add image file extention

yocto/fetch-sources-for-recipes.sh
Right now it is impossible to pass additional parameters to bitbake
which would change what would be fetched during the fetch phase.
This change takes all aditioal arguments and passes them to bitbake,
this way one can for example add -c populate_sdk which would trigger
fetch for different components then without it.
This change is backwards compatible, it just looks for additional
parameters.
=> yocto: Add optional params to fetch all

yocto/build-testexport.sh
script dedicated to build testexpert archive to perform runtime testing
on end device
Signed-off-by: Dmytro Iurchuk <DIurchuk@luxoft.com>
=> yocto/build-testexport.sh: File creation

yocto/runqemu-smoke-test.sh
Specifically:
1. do not hardcode uid/gid. Rather use ones actually assigned to the user running the script.
2. do not use setcap. setcap has the unfortunate side effect of no longer loading correct libraries (from qemu sysroot), and instead falling through to host libraries which may mismatch or be absent altogether.
=> Correctly create and use tap devices in runqemu-smoke-test

yocto/json2junit.py
Recent Yocto versions added support for this, so if the duration
is present it is written into the junit (time is a valid paramer
with the same meaning).
Signed-off-by: Alexander Kanavin <alex.kanavin@gmail.com>
=> json2junit.py: write the test duration if provided in json

yocto/json2junit.py
Without this, the resulting report cannot distinguish between different runs for the same test case
This causes xunit reports to be wrongly displayed in Jenkins because it cannot distinguish different runs for the same test case when they have the same name. Then, tests reports are displayed in random order, and when you click a specific report you might get the wrong one.
=> yocto/json2unit.py: add timestamp to test case name

yocto/json2junit.py
On the previous PR (https://github.com/Pelagicore/vagrant-cookbook/pull/107) I had mistakenly pushed a commit-amend to the opened PR with the wrong var used. (really sorry for that)
The original change was supposed to be only the addition of `start_time` to the `testcase_name`
This restores the part that was wrong.
=> yocto/json2unit.py: hotfix wrong variable used in testcase_name

yocto/json2junit.py
Recent Yocto versions added support for this, so if OE tags
are present it is written into the JUnit as properties
Signed-off-by: Oleksandr Pozniak <oleksandr.pozniak@daimler.com>
=> json2junit.py: write OE tags if provided in json
