deps/sphinx-dependencies.sh

We use 'seqdiag' for diagrams in the Sphinx docs

Added diagram generation tool

---

deps/sphinx-dependencies.sh

makes texlive packages optional for sphinx

---

deps/yocto.sh

Added missing dependencies required by Yocto "Morty" 2.2.

Add dependencies for Yocto 2.2

---

deps/sphinx-dependencies.sh

Needed for whenever someone wants to use activity diagrams.

Adds actdiag for sphinx setup.

---

build/build-documentation.sh
build/clang-code-analysis.sh
build/cmake-builder.sh
build/cmake-git-builder.sh
build/qmake-git-builder.sh
build/qt5-git-builder.sh
deps/softwarecontainer-dependencies.sh
system-config/setup-ccache-and-icecc.sh

This installs ccache and icecc and sets it up.

adds ccache/icecc setup script

---

deps/softwarecontainer-dependencies.sh
system-config/vagrant-reload.rb

Also removes some extra spaces in the reload file.

Make sure lxc dir is removed before clone

---

system-config/grub-enable-cgroup-memory.sh

Fixes an erroneous grep in grub config

---

system-config/setup-ccache-and-icecc.sh

fix small ccache/clang issue

---

build/cmake-git-builder.sh
build/qmake-git-builder.sh
build/qt5-git-builder.sh

Use environment variables as in parameters to the script in order to
allow optional parameters. This also improves code by being more
self-documenting in Vagrantfiles (since the environment variable name
gives you a hint of what the parameter is for).
This also adds support for not wiping the source directory of the qmake
project bein built.
WARNING: The default behavior of this script HAS CHANGED where the
source directory is now NOT removed per default. In order to remove the
source directory, please set the WIPE_SRC_DIR parameter to "yes".
Signed-off-by: Jonatan Pålsson <jonatan.palsson@pelagicore.com>

qmake-git-builder: Use params from env

---

build/qt5-git-builder.sh

Signed-off-by: Oleksandr Kravchuk <oleksandr.kravchuk@pelagicore.com>

qt5-git-builder: init repo before checking out revision

---

deps/softwarecontainer-dependencies.sh

lxc: Distro is autodetected if the flag is removed

---

system-config/grub-enable-cgroup-memory.sh

Change the actual grub cmdline, not the default one

---

deps/softwarecontainer-dependencies.sh

Remove lxc packages before installing lxc from scratch

---

system-config/systemd-network-startup-timeout.sh

Adds a script to shorten systemd network startup timeout

---

deps/pytest-and-dbus-testing-dependencies.sh

pytest deps: Add psutil for testing

---

deps/pytest-and-dbus-testing-dependencies.sh
deps/softwarecontainer-dependencies.sh

deps: add python3 along python2 stuff

---

deps/yocto.sh

yocto deps: add gcc/g++ multilib

---

yocto/runquemu-smoke-test.sh

Add script for smoke testing images with bitbakes built in test mechanism.
Signed-off-by: Henrik Hugo <hhugo@luxoft.com>

Add smoke test script

---

deps/yocto.sh
yocto/runquemu-smoke-test.sh

This fixes some dependencies and capabilities needed to run QEmu and access the tun0 interface.
The capabilities given to QEmu are very generous, but I don't forsee this causing security issues.

Fix qemu quirks

---

yocto/run-in-build.sh

This can help simplify other scripts.

Add script to run yocto commands

---

yocto/shortlog.sh

In case there are multiple commits, it is safe to diff HEAD with master

Diff with HEAD and master to get the correct result

---

yocto/build-images.sh
yocto/build-sdk.sh
yocto/fetch-sources-for-recipes.sh
yocto/runqemu-smoke-test.sh

Signed-off-by: Chuan Jin <cjin@luxoft.com>

Replace duplicated code with init bitbake script

---

yocto/run-bitbake-tests.sh
yocto/runqemu-bitbake-test.sh

WIP: runqemu-smoke-tests: add bitbake tests posibility

---

yocto/run-bitbake-tests.sh

Add bin/bash to the script and fix the copyright ownership details 

run-bitbake-tests.sh: add interpreter of the script

---

yocto/build-images.sh
yocto/build-sdk.sh
yocto/fetch-sources-for-recipes.sh
yocto/runqemu-smoke-test.sh

add sourcing to the scripts instead of calling another script

---

yocto/run-bitbake-tests.sh

run-bitbake-tests:add sourcing

---

yocto/build-esdk.sh
yocto/build-images.sh
yocto/build-sdk.sh

yocto bitbake scripts:improve readability of console

---

yocto/run-yocto-check-layer.sh

Signed-off-by: Tariq Ansari <tansari@luxoft.com>

Add script to run yocto compatibility check

---

yocto/shortlog.sh

Allow comparing against a given manifest file, which might not be part
of the project's git history. This is useful in those cases where the
manifest file contains links to branches and not to git revisions; in
that case, a manifest with proper git revisions can be generated with
the `repo manifest` command.
Also fix a couple of errors, such as the invocation of "repo forall" in
get_changes().
Signed-off-by: Alberto Mardegan <alberto.mardegan@luxoft.com>

shortlog.sh: Take the old manifest as a parameter

---

deps/softwarecontainer-dependencies.sh

Signed-off-by: Tariq Ansari <tansari@luxoft.com>

softwarecontainer-dependencies.sh: use lxc 3.1.0

---

deps/softwarecontainer-dependencies.sh

Signed-off-by: Tariq Ansari <tansari@luxoft.com>

softwarecontainer-dependencies.sh: use lxc 3.1.0 tag

---

yocto/shortlog.sh

Improve the format of the generated shortlog:
- quote the LOG variable to ensure that the whitespace will be
preserved;
- add more empty lines to visually separate layer reports;
- print the layer name, not its full path.

shortlog.sh: Improve formatting

---

yocto/runqemu-smoke-test.sh

Please see the commits for details.

yocto/runqemu-smoke-test.sh: test all requested images and not just the first one
